### ISSUE TITLE
error java.lang.RuntimeException: could not find a configuration file to load. looked in the classpath (as a "resource") and on a file system via "conf" system property

### ISSUE THREAD

**Issue by satishblr** [MoriTanosuke/docker-hface#1]
i am running with this command 
_dzdo docker run --rm -p 8000:3000 -v $(pwd)/hface.conf:/etc/hface.conf:Z moritanosuke/docker-hface_

but i am seeing this error 

> java.lang.RuntimeException: could not find a configuration file to load. looked in the classpath (as a "resource") and on a file system via "conf" system property

**Comment by MoriTanosuke** [comment]
Sorry, I can not reproduce this. I rebuild the image from the latest commit, here is my output:

````bash
$ docker run --rm -p 3000:3000 -v $(pwd)/hface.conf:/etc/hface.conf docker-hface
2018-06-20 05:29:02.252:INFO::main: Logging initialized @704ms
2018-06-20 05:29:03.936:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
2018-06-20 05:29:03.957:INFO:oejs.ServerConnector:main: Started ServerConnector@33850dc2{HTTP/1.1}{0.0.0.0:3000}
2018-06-20 05:29:03.958:INFO:oejs.Server:main: Started @2410ms
Started server on port 3000
````

Can you give the output of this command please:

    echo $(pwd)/hface.conf

I also notice that your command line has an additional `:Z` after the path to the mounted volume `/etc/hface.conf`. Is this intentional?
